### ISSUE TITLE
need way to specify in that component accepts 0, 1, or many children

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#102]
perhaps just 3 more macros:

```ruby
expects_no_children
expects_one_child
expects_children
```

**Comment by catmando** [comment]
Rationale:  React.js has a similar mechanism...

The "children" are part of the interface of the component.  Does this component expect to receive children?  How many?

I would update the above with an `:optional` keyword (as in `expects_one_child :optional`  

or we could skip it ?

**Comment by ajjahn** [comment]
Normally, I'm all for explicit declaration, but I think this one place in particular where React gets it wrong.

In React, `this.props.children` is an opaque data structure. React provides some top level API utilities for interacting with that data structure, but the behavior is surprising.

The name children would make you think it's always going to be a collection. But it's not:

* Sometimes children is populated with many children. Like an array with multiple items.
* Sometimes children is just a single child element. Not an array at all.
* Sometime children is null.

This means you have to do type checking and other probing to figure out how to proceed.  Wouldn't it be less surprising if children were always an array, even if the array is sometimes empty or just a single child?

```ruby
children = []
children.each do |child|
  child.do_some_thing # => with an empty array, this is skipped right over. Nice!
end
```

The current implementation of children fixes it by always returning an enumerable object even if it's empty. I think that's a big improvement.

Right now the params validator automatically adds a rule to optionally accept the children param. If we want to tighten this up and allow children to be represented in a declaration, we could add the ability to define the children param as required. Then there will be a warning if no children are passed.

**Comment by catmando** [comment]
Yes you talked me out of it.  You are right we have a more robust interface and it encourages more robust component design.  If a component takes children it should be obvious from its function (`DialogBox` for example would almost have to take children or would have a required `React::Element` type param) 

And a well crafted component that takes children should act sensibly no matter if there is zero, one, or many children.

So case closed.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#102
