### ISSUE TITLE
Intelligently accept React::Elements

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#103]
given this:

```ruby
class MyComponent < React::Component::Base
  param :foo type: React::Element
  ...
end
```

we should then be able to say

`MyComponent(div { "hello"})` instead of `MyComponent(div {"hello"}.as_node)`

This may not be easily implementable but it sure would be nice.  I'm just not sure if apply as_node inside of another components' validator will work, because by that time we may not know the rendering context.

Furthermore if the param is any other type that responds to `to_s`  we should automatically convert it (by doing a `.to_s.span`)  This we can easily do.

**Comment by catmando** [comment]
Looks like we are sort of already doing this in 0.7... any Elements passed to other other elements are automatically removed from the rendering buffer.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#103
