### ISSUE TITLE
clean out all the puts statements showing up on server

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#116]
there are some puts statements or some kind of logging like this:

************************** React Server Context Initialized Components::Sessions::New *********************************************

showing up on the server

**Comment by ajjahn** [comment]
@catmando Removed the client side `puts` statements as well. We definitely don't want those in production. It would be nice to implement a proper logger that will obey log levels per environment.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#116
