### ISSUE TITLE
auto-adding of 'px' suffix to style values 

### ISSUE THREAD

**Issue by Thermatix** [zetachang/react.rb#117]
I've noticed that when I try to set the z-index of a page element using style, `px` gets added to the value automatically but z-index needs a number not a pixel value. 
So the web-browser won't accept it as a valid value and so Z-index effectively doesn't work because of it.

**Comment by ajjahn** [comment]
@Thermatix Can you verify that this isn't an issue with plain old react.js v13?

**Comment by Thermatix** [comment]
I think it might be react.js becuase of this (post)[https://facebook.github.io/react/tips/style-props-value-px.html]

**Comment by ajjahn** [comment]
Are you specifying the z index with snake case: `{ zIndex: 1 }`?

**Comment by Thermatix** [comment]
I was doing `{"z-index" => -1}` I changed it to snake case and it stopped doing the px thing.

**Comment by ajjahn** [comment]
Perfect!

**Comment by catmando** [comment]
This is related to #108

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#117
