### ISSUE TITLE
if params have embedded native objects you make get failures on rerendering

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#126]
I cannot reproduce this problem in test environment.

However the situation is that we have params coming in that somehow nested in the param is a native object.  When the component is rerendered the fix to #125 causes rendering to fail.

The fix to #125 checks the old param against the new param using ==.  == fails if nested within either object is a native object (seems like a bug in Opal IMHO)

The fix is to use equal? instead of ==.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#126
