### ISSUE TITLE
react.rb site cursor black

### ISSUE THREAD

**Issue by awwaiid** [zetachang/react.rb#128]
The cursor in the code examples on react.rb are black, which is almost invisible. In my browser I switched it to white and it is much better. I'd submit this as a PR, but I don't know where that CSS lives :)

**Comment by catmando** [comment]
@awwaiid awesome... I was hoping someone could fix this!  The documentation site is here: https://github.com/reactive-ruby/reactive-ruby.github.io.  Feel free to do a PR...If you need any help getting the doc site up feel free to ask here:  https://gitter.im/zetachang/react.rb

**Comment by awwaiid** [comment]
Thanks for the pointer. I opened https://github.com/reactive-ruby/reactive-ruby.github.io/pull/23, so am closing this!

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#128
