### ISSUE TITLE
[discuss] React Native Support

### ISSUE THREAD

**Issue by zetachang** [zetachang/react.rb#14]
[React Native](http://facebook.github.io/react-native/) for iOS is released yesterday!

To integrating with Opal Ruby tool chains, providing a [packager API](https://github.com/facebook/react-native/tree/master/packager) compatible version of our own may be a start point. 

I haven't started to work on it,  so feel free to leave any suggestions on possible direction! :smile:

**Comment by zetachang** [comment]
I think Sprockets will be a nice replacement for packager. But what bother me currently is that do we need to support CommonJS module (which react-native is structured currently)? Or just append all the library as we did now.

To support CommonJS module, there exists [browserify-rails] (https://github.com/browserify-rails/browserify-rails) which is a Sprockets processor wrapping browserify. Haven't try it out but sounds like a valid solution.

**Comment by sfcgeorge** [comment]
React Native looks powerful but I'd much rather write Ruby, so :+1: for this :)

**Comment by zetachang** [comment]
@sfcgeorge got a sample project up and running here (https://github.com/zetachang/opal-native), feel free to leave message here or open an issue in the repo. :smiley:

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#14
