### ISSUE TITLE
Rails 5.rc1: `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007fd1698ee210>

### ISSUE THREAD

**Issue by fcarucci-zz** [zetachang/react.rb#145]
Part of the callstack:

Did you mean?  asset_host (NoMethodError)
    from /Users/fcarucci/.rvm/gems/ruby-2.3.0@frontend/gems/reactrb-0.7.42/lib/reactive-ruby/rails/railtie.rb:5:in `block in <class:Railtie>'
    from /Users/fcarucci/.rvm/gems/ruby-2.3.0@frontend/gems/activesupport-5.0.0.rc1/lib/active_support/lazy_load_hooks.rb:36:in`execute_hook'
    from /Users/fcarucci/.rvm/gems/ruby-2.3.0@frontend/gems/activesupport-5.0.0.rc1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /Users/fcarucci/.rvm/gems/ruby-2.3.0@frontend/gems/activesupport-5.0.0.rc1/lib/active_support/lazy_load_hooks.rb:44:in`each'

**Comment by fcarucci** [comment]
My mistake.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#145
