### ISSUE TITLE
Update to latest Opal.rb

### ISSUE THREAD

**Issue by krainboltgreene** [zetachang/react.rb#15]
Since the latest release of this gem there have been more official releases of opal.

**Comment by elia** [comment]
This has been discussed, but being source-maps availability a primary concern I _officially_ suggest to wait until 0.8 :smiley_cat:

**Comment by krainboltgreene** [comment]
I agree for releases, but it might be a good idea to have a "unrestricted version" for master since a few people (myself) point to github. We can fix them to a specific version on release.

**Comment by elia** [comment]
Or have a branch pointing to master in preparation of the 0.8 release

**Comment by krainboltgreene** [comment]
I forked the repo and moved to latest, got this error:

```
A file required by "ghostryder" wasn't found.
A file required by "react" wasn't found.
A file required by "react/component" wasn't found.
can't find file: "./ext/string"
```

**Comment by zetachang** [comment]
Actually there is already a pull request upgrade opal to the latest version (#10) which also fix the error you mentioned. And I think I will go for @elia's suggestion to create a new branch.

**Comment by zetachang** [comment]
We got a new branch (https://github.com/zetachang/react.rb/tree/opal-0.8) prepared for up comping 0.8 release.

**Comment by ajjahn** [comment]
Closing now that 0.8.0 is supported.
