### ISSUE TITLE
Warning on setting props.onEventName of React component

### ISSUE THREAD

**Issue by zetachang** [zetachang/react.rb#18]
```
Warning: Don't set .props.onClick of the React component <input />. Instead, specify the correct value when initially creating the element. The element was created by TodoItem.
```
## Reason
If you are on React.js v0.13, you might see this warning, since upon 0.13, props will be immutable. 

## Solution
To make the syntax `on(:event_name)` still work. We will shift to `React.cloneElement` (https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement).

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#18
