### ISSUE TITLE
How robust is this?

### ISSUE THREAD

**Issue by akshatpradhan** [zetachang/react.rb#20]
I'm curious how well can this integrate with the typical frameworks. For example, will this work inside apps that incorporate many frameworks (e.g animation.css, bootstrap.css, highcharts.js) inside their application. 

Are there any examples of large enterprises using this in their rails app?

Let me know!

**Comment by zetachang** [comment]
To be honest, I haven't used this in production yet, but as you see. react.rb is actually a thin wrapper over react.js. 

If you are asking production usage of opal ruby, maybe @adambeynon, @elia could provide some insight.

**Comment by akshatpradhan** [comment]
I'm interested in this library over using React.js. I can read these Ruby examples more easily than I can the Javascript examples.

**Comment by zetachang** [comment]
Glad to hear, basically you can treat opal ruby as language like coffee script, it's just ruby compiled to JS. And it doesn't place any strict limitation on what framework you use, some any css / js framework could be easily integrated. 

Hope this clarify :smile:

**Comment by elia** [comment]
I had Opal In production for years on several websites, some of them with millions of monthly visits with the same code for both desktop and mobile. I started using it in production at v0.3. 

Hope this raises confidence a bit. :)

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#20
