### ISSUE TITLE
change define_state 

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#21]
I propose changing define_state to work like this:

```ruby
define_state do |v1, v2, v3|
  v1 = "initial value"
  v2 = "some other initial value"
  # v3 never gets initialized
end
```
You can also do 

`define_state do |v1 = "foo", v2 = "bar"| end`

which is very nice too.

This is possible after ruby 1.9 because you can get the list of parameter names for the block.

This syntax will work only if there are NO define_state parameter... i.e. define_state(:x) will continue to work as it does today.

I will be happy to implement this and do a pull request, I just want some feedback that this will be acceptable.

**Comment by catmando** [comment]
I'm going to close this for now... This is not going to work as I thought it would.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#21
