### ISSUE TITLE
remove sprockets-es6 dependency

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#23]
How hard is going to be to do this?  sprockets-es6 is experimental, and also makes this incompatible with rails 3.2

**Comment by zetachang** [comment]
Actually this is the top priority I am going to fix next. Other than making
it incompatible with rails, it also break the source map support.
catmando <notifications@github.com>於 2015年4月29日 週三，下午6:30寫道：

**Comment by catmando** [comment]
thanks... btw its interesting... all specs pass without it?  How is that possible?

**Comment by zetachang** [comment]
This has been addressed in v0.3.0, also sprockets dependency has been loosen to make sure source map is not broken. 

@catmando, I don't know how to test source map.... given that they are server side logic while all the specs are written against client side behavior.

**Comment by catmando** [comment]
for source map testing you could look at how Opal does it I suppose.  

For me its not urgent.  I am prefering using the DSL approach.  Ends up with very clean looking code, and no need for special editor support.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#23
