### ISSUE TITLE
Need a way to deal with objects changing state (i.e. arrays)

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#24]
For example

```ruby
define_state(:foo) { ['joe', 'fred'] }

def add_friend(friend) 
  foo << friend
end
```

This does not work as `foo << friend` updates the array object, but there is no way to know that the foo state has been updated.

I have implemented a couple of solutions, and am interested in which people would prefer:

1) define foo! method that will return an object that wrap the current value of foo, and observe any changes to that object.   So you can write

```ruby
def add_friend(friend)
  foo! << friend
end
```

2) define foo! method that simple does `foo = foo` to indicate a state change.  This would return self so that the methods could be chained

```ruby
def add_friend(friend)
  foo << friend; foo!
end
```

or

```ruby
def add_friend(friend)
  foo << friend
ensure
  foo!.bar!
end
```

2b) In addition the Proc class can be updated so this works

```ruby
lambda { |new_friend| foo << new_friend }.foo! 
```

Just looking for people's input, preferences, or other ideas!

**Comment by zetachang** [comment]
Thanks for pointing this out, I think this could be a common mistake given that the original `setState` is wrapped inside the setter.

Currently, you can write as below, 
```ruby
def add_friend(friend)
  self.foo = foo << friend; self
end
```

To get the benefit of brevity and also make it chainable.

**Comment by catmando** [comment]
I understand that you do as you said...

My intention is to add a solution that will read cleaner and be shorter.

I have implemented the solutions above, but feel that just adding the foo! method is the easiest and cleanest.

I.e. `foo! << friend` is equal to `foo << friend; self.foo = foo`

If I do a pull request with this will you accept it?

**Comment by zetachang** [comment]
I think I get your point now, looks like a nice to have feature. Feel free to open up a pull request :+1:

**Comment by catmando** [comment]
i've made some more improvements to this... expect a pull request soon, but first I am integrating with some real code to see how everything feels.

basically there is now a foo! method that can be either used as foo!('new value') (equivilent to self.foo = 'new value')
or if no parameter is provided then foo!() returns an object that will update after any method calls on foo.

this shortens things up nicely.

In addition I added two class methods `require_param` and `optional_param` that will declare a parameter. The difference is these methods will also create methods that can read the parameters directly.

I.e. `require_param :foo, type: String` will require a foo parameter and will create a foo method that returns that parameter.

Finally if the type of parameter is `Proc` then the created method will call the proc.  So

`require_param :foo, type: Proc`

then 

`foo 1,2,3`

will send 1,2,3 to whatever Proc foo got bound too.

Altogether these changes clean things up so that things read really nicely.

Oh yeah two other things:

You can say `class MyComponent < React::Component::Base` instead of including `React::Component`

And any class that responds to 'render' can be used in the rendering dsl.  So you can say
```ruby
div do
  my_component param_1: 'Joe', param_2: 'Fred'
end
```
As long as an instance of MyComponent responds to render...

How does all that sound :-)

**Comment by zetachang** [comment]
Hey, thanks for taking time making this suggestion. 

> or if no parameter is provided then foo! returns an object that will update after any method calls on foo. 

How is this going to be implemented? A wrapper object which will delegate all method invocations? 

> In addition I added two class methods require_param and optional_param that will declare a validated parameter. The difference is these methods will also create methods that can read the parameters directly.

We currently got a `params` class methods, it becomes complicated for me to choose which one to use if another `require_params`, `optional_params` is introduced. So maybe add a new parameter, that's say `accessor: true`. So you can write like this,

```ruby
params do
    requires :foo, type: Proc, accessor: true
end
```

> Finally if the type of parameter is Proc then the created method will call the proc. 

This is actually quite neat,  :+1:  on this.

> You can say class MyComponent < React::Component::Base instead of including React::Component

Would you mind elaborating more on why having a base class rather than current module approach? The initial design decision made is to allow every Ruby class got render defined could be valid component. `React::Component` only provide helper methods. And there is a lot of refactoring work for `React::Component` on #17 , so I will suggest postponing this until it's done.

> And any class that responds to 'render' can be used in the rendering dsl.

:+1:  on this.


Last but not least, would you mind open separate pull requests for these features? Thus we can review and merge them faster. :smiley:

**Comment by catmando** [comment]
Thanks for the feedback... will discuss more on the pull request. 

As I am using this in a real app, I am making adjustments to the API as I go

**Comment by catmando** [comment]
Okay.. I setup a WIP pull request... your comments on these items would be great.

**Comment by ajjahn** [comment]
@catmando This is implemented as part of the state observer (! bang method) API.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#24
