### ISSUE TITLE
how to get react.js source included?

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#26]
I am working with the 0.8 opal branch
it does not include react-source (except in development)

The only way I can see to get react.js loaded is to include it in the index.html file?

Am I missing something?

Over on the opal gitter.im board, they figured you had a plan :-)

**Comment by zetachang** [comment]
Yeah, I've noticed the namespace collision, will switch `Opal::React` soon. And when #19 is done, `react-source` will be runtime dependency and added to sprockets assets path automatically.

> The only way I can see to get react.js loaded is to include it in the index.html file?

I am quite fine with this approach, since it's transparent to user who already familiar with sprockets.

**Comment by zetachang** [comment]
It's done in react-v0.13 branch, https://github.com/zetachang/react.rb/tree/react-v0.13#reactjs-dependency

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#26
