### ISSUE TITLE
Cannot read property ‘firstChild’ of undefined

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#27]
I am getting this error.

The web says this is caused by having 2 different versions of React.

I have tried every way to make sure that I only have one version, and I am still getting this error.

It is happening on the second render to a component, IF I am using opal-rspec in the browser.

I do not believe this is happening unless I am running opal-rspec.

I have done some basics like putting a console.log statement at the start of the react.js (unminimized) file and according to that log react.js is only loading once.

I have also made sure that react-source is not in my gem file.

Any clues or things to try would be greatly appreciated.

**Comment by catmando** [comment]
Okay it seems like this is something to do with react's state between the rspec tests.   If I move the "failing" test to be the first test, everything is fine.

I do have `after(:each) { React::API.clear_component_class_cache }` in the test but it makes no difference.

So I am pretty sure somehow the opal-rspec environment is clobbering react

**Comment by catmando** [comment]
Okay I got this figured out -- the problem occurs if a component that was used in a static rendering is later asyncronously updated.  That seems to screw everything up.  

I don't know yet if this is a problem with opal, react.rb, or perhaps with reactjs

**Comment by zetachang** [comment]
That's weird, would you mind pasting the code which failing the test?

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#27
