### ISSUE TITLE
Need for RubyRacer?

### ISSUE THREAD

**Issue by wied03** [zetachang/react.rb#29]
Kind of a dumb question I'm sure, but why is this dependency in here?

**Comment by zetachang** [comment]
Hi, the reason is that I failed to make the JSX transformer works in execjs default js runtime (which is JavaScriptCore on OS X). So I thought it will be easier if this gem by default depends on a runtime which just works.

Are you trying to use this on some other JS runtime and got problems?

**Comment by wied03** [comment]
No good reason, just a bit more dependencies with v8, etc. than what I typically have with rails (just execjs + node)

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#29
