### ISSUE TITLE
render should not fail silently

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#34]
It would be a big help with debug if render would not fail silently, but instead simply print the exception raised etc.

Perhaps this is some setting in reactjs?  Otherwise I am thinking that we could add a method render_debug to the component class, which calls render and prints any error message.

render_debug would be called by the API if it was available AND some kind of config switch was set.

**Comment by catmando** [comment]
added this to my currently open PR

**Comment by ajjahn** [comment]
@catmando I'm assuming this has long since been implemented, so I'll close it. Reopen if not.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#34
