### ISSUE TITLE
how to render children in dsl?

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#35]
Its not clear (or perhaps there is no way) to render children in the DSL.

For example 

```ruby
class ReverseDiv
  render
    div do
      params[:children].reverse.each do |child|
        # what do I do here? 
      end
   end
end

**Comment by zetachang** [comment]
Yeah, you are right on this.. any suggestion? 

I am thinking of maybe passing a builder handler as the argument of the block, thus you can manually append element on it.

```ruby
class ReverseDiv
  render
    div do |handle|
      params[:children].reverse.each do |child|
        handle << child
      end
   end
end
```

**Comment by catmando** [comment]
why not just let `present` check its parameter?  If its of type React::Element then it just pushes it on.

By the way any reason we could not use `display` as an alias for `present`? 

Another alternative is to add a "display" or "present" method onto React::Element 

So then you could say `child.display`... I like this the best for the following reason:

If you have children then you are probably going to want to clone them to set props on them (http://jaketrent.com/post/send-props-to-children-react/)

So... if we go with child.display, the display method can check, and if there are arguments then it first does a clone of the child and treats the arguments as the new props...

We could also add the display method to string (not 100% sure I like that) so that strings can be emitted as well.

Finally we would need a way to check to child's component class.  Not sure if there is already a way to do this in react.rb, but if not we could redefine is_a? for React::Elements to check the underlying component class type.

Cool?

Jakes example would then read like this:
```ruby
class RadioOption
  include React::Component
  def render
    label do
      input(type: :radio, value: params[:value], name: params[:name])
      params[:label].display 
    end
  end
end

class RadioGroup
  include React::Component
  def render
    div(className: "radio-group") do
      children.each do |child|
        child.display child.is_a? RadioOption ? {name: params[:name]} : *[] 
      end
    end
  end
end
```

**Comment by zetachang** [comment]
Actually, I just found out according to the current implementation, the yielded result of the block provided to the `React.create_element` or dsl methods would be used as the children. (if none of other dsl methods are invoked in the block), so you could write as,

```ruby
class ReverseDiv
  render
    div do
      params[:children].reverse
   end
end
```

Also, I will suggest using `React.cloneElement` (https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement) (which is not yet integrated to react.rb yet) which is more verbose to people already experienced with reactjs.

> Finally we would need a way to check to child's component class. Not sure if there is already a way to do this in react.rb, but if not we could redefine is_a? for React::Elements to check the underlying component class type.

`React::Element#element_type`(https://github.com/zetachang/react.rb/blob/master/lib/react/element.rb#L9) may be a start point to do this. I won't suggest redefining `is_a?` given that only the actual rendered component (the one returned by `React.render(element)`) is the instance of the component class.

**Comment by catmando** [comment]
Thanks I will work on this with this approach

**Comment by ajjahn** [comment]
Fixed.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#35
