### ISSUE TITLE
Collision with Opal-JQuery

### ISSUE THREAD

**Issue by wied03** [zetachang/react.rb#36]
(discovered in pull request).

Another problem I'm seeing here is that react.rb ends up inadvertently defining a top level Element class (in addition to the React::Element class). This conflicts with opal-jquery and makes opal-jq pretty much unusable.

I added a test to try and verify this is fixed and I tried to format the js code in element.rb better. I'm not quite proficient enough in JS at the moment to understand what that code is doing, but it looks like you're cleverly trying to make the React Element objects that React itself produces inherit from this class. This just seems to be a side effect.

A simpler way (I think) to see this problem is to compile the following:
```
class User
  attr_accessor :joe
  def initialize
    @joe = 'howdy'
  end
end

module Mod
  class User < %x{
    (function() {
      var f = function() {};
      f.prototype = Object.getPrototypeOf(String);
      return f;
    })()
  }
    def other_method
      'nope'
    end
  end
end

puts User.new.joe
```

**Comment by wied03** [comment]
Doing things this way works in this case, will try and apply it with React now:
```
class Element
  attr_accessor :joe
  def initialize
    @joe = 'howdy'
  end
end

module Mod
  class Element < %x{
    (function() {
      // can't get the prototype for this directly, need to go go in a roundabout way
      var r = new ReactStub("from opal");
      var f = function() {};
      f.prototype = Object.getPrototypeOf(r);
      // self is in the module, so we'll place a stub super class right next to our real one in this Mod module
      // by passing in f, Opal will build a Ruby class from the prototype we derived
      return Opal.klass(self, f, 'ReactStub', function() {});
    })()
  }
  
    def other_method
      `this.nativeMethod()`
    end    
  end
  
  # Now that we've created the stub class that uses our original ReactStub prototype logic, replace that with the
  # Opal class's constructor. This will build a proper Opal object + run our original ReactStub constructor/prototype logic
  `ReactStub.prototype = Opal.Mod.Element.$$proto;`
end

# Should be undisturbed
puts Element.new.joe
usermod = `new ReactStub("ssss")`
# should print out "hello ssss"
puts usermod.other_method
```

**Comment by wied03** [comment]
Best way to fix this turns out to be in Opal itself, see issue https://github.com/opal/opal/issues/883. Since it looks like my pull request will be accepted, I'll close this.

**Comment by zetachang** [comment]
This is actually weird... thanks for pointing this out.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#36
