### ISSUE TITLE
isomorphic execution

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#38]
Does this work?

There are two strategies I think:

1) run opal on the server
2) make a server version of react.rb that calls through to JS

2) would be faster but more maintenance

**Comment by zetachang** [comment]
I will vote for 1) since I can expect there might be weird code could not be run purely in ruby because x-interpolation. Also they will also leads to a maintenance headache to implement a incomplete reactjs version in Ruby.

**Comment by wied03** [comment]
Since I started experimenting with react.rb into my existing app with React components written in JS, the server side rendering code of react_rails has worked great for me, including Opal coded components.

**Comment by catmando** [comment]
I agree and am closing the issue.  I have a complete integration with react-rails and it works great.

**Comment by zetachang** [comment]
It would be nice if you guys could share some working example of integration with rails & react_rails. :wink:

**Comment by tnedich** [comment]
@zetachang  I would like to see small example :+1:

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#38
