### ISSUE TITLE
change name space

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#39]
I keep running in to problems becuase react.rb is using the same name as react.js.  Just crashed into this again trying to integrate with react-rails.

I suggest the file name be changed to opal-react (consistent with opal-jquery etc.)  Module name can stay React.

I have tried this on my WIP branch, and it works great.  After changing the file names to be opal-react, I was able to integrate without any difficulty with react-rails.

Please let me know your thoughts on this, and how to proceed re: pull request etc, as I want to go ahead and get this fully integrated with react-rails asap.

**Comment by zetachang** [comment]
Actually the namespace issue has already been addressed in https://github.com/zetachang/react.rb/commit/75896a8acefc7f20d9db612b4cb5ee3c94c5e0d1. You can try it on the `react-v0.13` branch.

**Comment by catmando** [comment]
okay!  great... I will work on merging my WIP with v0.13 later this week.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#39
