### ISSUE TITLE
make example apps into standalone repos?

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#42]
Just chatting on gitter, and realized it might be easier for people if the example apps each had their own repo, so you can just clone to example app, and away you go.

Not a big deal of course.

**Comment by hswick** [comment]
After cloning react.rb and cding into examples

Only basic-jsx, react-tutorial, and todos are available.

So separating these out would make it a lot easier for people to try it out, or at least fixing this bug.

**Comment by catmando** [comment]
@hswick - be aware that most work is being focused on the reactive-record branch that while upwards compatible with original react.rb has a lot of dsl features that make jsx obsolete.

**Comment by ajjahn** [comment]
@catmando Is this still something you want to do?

**Comment by ajjahn** [comment]
abbf94fbcade561df63d0e72968a567ffd2501ea closes this.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#42
