### ISSUE TITLE
Benefit to using React.createClass ?

### ISSUE THREAD

**Issue by wied03** [zetachang/react.rb#43]
I admittedly don't have an in depth understanding of exactly how react.rb maps to the underlying JS code, but would there be benefit in "caching" a Ruby/Opal class that includes React::Component such that https://github.com/facebook/react/blob/v0.13.1/src/classic/class/ReactClass.js is used?

It looks like, from the React code, there are some items it gets out of the way that might be nice for performance if a given component is used in several places.

That said, that would not play well with the monkey patching "feature" of Ruby

Maybe just calling createClass the first time someone tries to use a class and then holding on to that (e.g. in top_level.rb/create_element)?

**Comment by catmando** [comment]
if you look at the api.rb file I think its doing something similar.  Certainly components are only created once.  Is this way you mean?  By the way there is a [gitter room](https://gitter.im/zetachang/react.rb) set up for react.rb, and might be a better place to discuss

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#43
