### ISSUE TITLE
0.13 branch not working with opal 0.7.2

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#47]
@zetachang @weid03  It seems like with opal 0.7.2 the 0.13 branch breaks where it is defining the component factory  specifically         `ctor.prototype = klass._proto;` klass._proto is undefined, I assume something changed in 0.7.2... do either of you know about this?

**Comment by zetachang** [comment]
It's known issue fixed by @weid03 in his PR, I will cherry pick them in
later today.

catmando
notifications@github.com>於 2015年6月10日 週三，下午9:11寫道：

@zetachang <https://github.com/zetachang> @weid03 It seems like with opal

**Comment by ajjahn** [comment]
@catmando I do believe this is fixed. Closing. Reopen if not.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#47
