### ISSUE TITLE
with on(:click) react event can't access standard DOM methods

### ISSUE THREAD

**Issue by classyPimp** [zetachang/react.rb#50]
`
class Sample
  include React::Component
  define_state(:comments){
    ["foo", "bar"]
  }

  def handle_that(e)
    p e.target.data('index') <----this not working
  end

  def render
    div {
      self.comments.each_with_index do |comment, index|
        p("data-index" => index.to_s) { comment }.on(:click) { |e| handle_that(e) }
      end
    }
  end
end
`

`p e` in handle_that returns Ract::Event object, `p e.target` returns Native paragraph object, but any other methods on p.target return "" or undefined, is it possible to access that target html, data attrs and so on? opal-browser and everything else is ok (using with rails).

**Comment by classyPimp** [comment]
my bad, everything is ok(( Native(`#{e}`) does everything

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#50
