### ISSUE TITLE
React::Event 's target can't be turned to Opal Jquery Element

### ISSUE THREAD

**Issue by classyPimp** [zetachang/react.rb#51]
```ruby
class Sample
  include React::Component
  define_state(:comments){
    ["foo", "bar"]
  }

  def handle_that(e)
    x = e.target <------returns dom element
    x= Element.find(x)
    puts x.html <-------nil returned
  end

  def render
    div {
      self.comments.each_with_index do |comment, index|
        p("data-index" => index.to_s, id: "foo") { comment }.on(:click) { |e| handle_that(e) }
      end
    }
  end
end
```

But if you do e.g. `x = `document.getElementById`; x=  Element.find(x); puts x.html` everything works.
Is it possible to instantiate react event's target element as Opal Jquery Element? `e.native_event.target` doesn't work either.

**Comment by zetachang** [comment]
I think the `e.target` return an opal native element.  Does `Element.find(x.to_n)` work?

**Comment by classyPimp** [comment]
yeah, right it works! Thanks for that. And separate thanks for react.rb! You rule!

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#51
