### ISSUE TITLE
With React::Component, calling "#on" on nested Elements throws away the callbacks (0.13)

### ISSUE THREAD

**Issue by dodecaphonic** [zetachang/react.rb#54]
This is due to rendering using blocks to define layouts and `@buffer` on `method_missing`. When evaluating those blocks, Elements will be created by recursively calling into the blocks, sharing a top-level array to gather the results. With a layout like:

``` ruby
def render
  button(type: "button").on(:click) do
    puts "Everybody say yeah!"
  end
end
```

the events are bound correctly because render will evaluate to what's returned by `Element#on`. However, doing it like this:

``` ruby
def render
  div do
    button(type: "button").on(:click) do
      puts "Everybody say yeah!"
    end
  end
end
```

Will ignore the button with the events, as it will latch onto the version inside the `@buffer` coming from div (i.e., the button WITHOUT the events).

If I understand correctly, using that buffer is just a way to collect what's rendered in nested blocks and finally render the topmost structure using `React.create_element`. Are the maintainers looking into this? Would it be ok to try and fix it?

**Comment by dodecaphonic** [comment]
Here's some options I've considered:

- Wrapping ReactElement completely, and delaying the transformation from an a Ruby Element into a ReactElement until the last minute. When transforming, explicitly weaving the tree into the evaluation and  avoiding constructing things with `method_missing`;
- _À la_ Elm, purescript-halogen and friends, making the tree very explicit by having a `children` or such property receiving an Array (doesn't look as good as the block syntax, though);
- Passing into each child block a context object that takes care of building the tree (which would probably help with #35, and perhaps loop similar to what's suggested there by @zetachang).

**Comment by catmando** [comment]
I believe this is fixed in the catprintlabs branch.  Basically follows the first solution suggested.

**Comment by dodecaphonic** [comment]
Great to hear, @catmando. Thank you.

**Comment by ajjahn** [comment]
@dodecaphonic Now in master branch... closing.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#54
