### ISSUE TITLE
Cannot use the original `Element` as `React::Element` overrided it

### ISSUE THREAD

**Issue by raysegantii** [zetachang/react.rb#57]
The compiled `React::Element` goes directly under `Opal` and the original `Opal.Element` is lost.

**Comment by wied03** [comment]
https://github.com/zetachang/react.rb/issues/36

**Comment by ajjahn** [comment]
@raysegantii Closing in light of #36.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#57
