### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by Thermatix** [zetachang/react.rb#58]
I'm getting this (title) message in the js console on the browser, I've included react via
```ruby
require 'react'
```

I'm using the `react-v0.13` branch.

**Comment by Thermatix** [comment]
nvm I didn't realise you needed to include the react.js file separately, I've done so and now it's working.

**Comment by MichaelSp** [comment]
Just stumbled upon this. Would be nice to have a hint in the installation section in the README.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#58
