### ISSUE TITLE
explicit component naming does not work in reactive-ruby branch and a Readme error

### ISSUE THREAD

**Issue by selectport** [zetachang/react.rb#60]
* This is from reactive-ruby branch *  ref. catmando conversation of 8/22 details as requested in gitter

I had an issue following the readme to get this working ... 
1.  First, comparing to the examples/rails_tutorials ... the component is named app/components/home.rb in the readme - but i could only get it to work if the component was in app/components/home/show.rb since the example component's name is Components::Home::Show ... 
2.  The implicit naming did not work when using render_component in the home_controller.rb - which i am pretty sure is because the component's class was Components::Home::Show and not home
3.  I did get it to work using this explicit render call in the controller : 

```
render inline: "<%= react_component 'Components::Home::Show', @rails_react_variables, { prerender: true} %>", layout: 'application'
```

and it worked correctly with prerender as both true and false.

4.  Side additional piece:  @catmando identified an issue with explicit naming, too ... mentioning it here because my initial attempt was to use the helper as in : 

```
render_component :hometest
```
where hometest (rather than home or home/show or whatever it needs to be !)  was the component name and that varied from the controller name ... this is a common requirement where i want to reuse toplevel components from different controllers ....

5.  Last part is a suggestion ... at least for the readme ... even though reactive-ruby can find the components via autoloading ...it would help new users of the gem if the readme referenced the app/views/components/home/show.rb 1:1 mapping between component name and component source directory ....

**Comment by ajjahn** [comment]
@selectport The reactive-ruby branch has now merged into master. In an effort to get these issues under control, can you update to the latest in the master branch and report back if you're still seeing this issue?

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#60
