### ISSUE TITLE
Example in reactive-ruby '/examples' throws console error

### ISSUE THREAD

**Issue by hswick** [zetachang/react.rb#62]
Actually two issues probably related to each other

I cloned the reactive-ruby branch and tried running the 'examples' example and had trouble, other examples seemed to work fine so I'm suspecting this has to do with the reactive-router dependency.

1. At first webrick would not start up because it could not find 'reactive-router' dir.
Then I cloned reactor-router repo, changed the dirname to 'reactive-router' and made sure it was in place where the gemfile was looking.

2. Webrick starts up but then page doesn't load with console error:
Uncaught RangeError: Maximum call stack size exceeded

Digging deeper the error seems to originate from this line:
          return (Opal.defn(self, '$method_missing', TMP_6 = function(n, args) {var $zuper = $slice.call(arguments, 0);
var $a, $b, TMP_7, $c, self = this, $iter = TMP_6.$$p, block = $iter || nil, name = nil, node_only = nil, e = nil, message = nil;
args = $slice.call(arguments, 1);

**Comment by catmando** [comment]
Thanks for the heads up... pretty sure I made some breaking changes in react-router, and never updated the example.... let me see if I can get this fixed ASAP for you.

**Comment by catmando** [comment]
Okay this got fixed.  It was actually a problem in reactive-router which had dependencies on some pull requests on opal, that I had forgotten we were still depending on.  So its fixed.  Also I noticed that the examples gemfile had a path spec instead of pulling the actual react-router gem, and that is fixed too.  So I believe it should all work fine.

**Comment by hswick** [comment]
Tried again after update and still having call stack issue above. 

Also doesn't look like the path changed for the reactive-ruby gem in the examples dir, still had to clone reactor-ruby outside of react.rb dir

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#62
