### ISSUE TITLE
reactive-ruby branch: set_state and =state seem to work in unexpected way

### ISSUE THREAD

**Issue by classyPimp** [zetachang/react.rb#63]
Looks like self.state[:foo] and self.foo (after define_state(:foo){"bar"}) live as different variables:
let:
```
class Show
      include React::Component 
      define_state(:liked) {"NO"}
      def render 
        div do     
          p do
            "#{liked}"
          end
          p do
            "click me"
          end.on(:click){
            handle_click
          }
        end
      end
      def handle_click
        self.liked = "yes"
        alert self.state[:liked]
      end     
end
```

would behave as expected.

BUT:

if in render you'll pass `#{self.state[:liked]}`, and in handle_click you'll use self.set_state(liked: "YES"), 
on initial load it'll render nil instead of NO , but after on_handle it'l show "YES"
And it leads to following:
when you define_state(:foo) {"something"}, you are expecting that state[:foo] are the same things, but looks like they live in different places.

**Comment by ajjahn** [comment]
@classyPimp Same goes for this one...

> The reactive-ruby branch has now merged into master. In an effort to get these issues under control, can you update to the latest in the master branch and report back if you're still seeing this issue?

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#63
