### ISSUE TITLE
reactive-ruby branch: force_update! causes method missing

### ISSUE THREAD

**Issue by classyPimp** [zetachang/react.rb#64]
Looks like force_update! (forceUpdate is not working), on call - raises: undefined method `force_update!' for #<#{react instance}>.

**Comment by ajjahn** [comment]
@classyPimp The reactive-ruby branch has now merged into master. In an effort to get these issues under control, can you update to the latest in the master branch and report back if you're still seeing this issue?

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#64
