### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by wied03** [zetachang/react.rb#65]
I see a ton of commits on the reactive_ruby branch without any changes to tests. Does this project intend to go back in a more "test driven development" direction?

**Comment by ajjahn** [comment]
@wied03 Have a look at #69. For now, my goal is at least *tested* if not *test driven*. #70 gets travis set back up (among other things).

Right now specs are only setup for the Ruby/Rails side of things. Still need to get the opal side of things set back up.

**Comment by ajjahn** [comment]
Tested: 5cbfd1adcb2d18c5f92f00beab18920fa2d650cc

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#65
