### ISSUE TITLE
HTML tag `p` break the element building DSL

### ISSUE THREAD

**Issue by zetachang** [zetachang/react.rb#7]
Since it will not trigger method missing..

**Comment by vais** [comment]
Some variation on this theme could work perhaps if you wrap it around your DSL?
```ruby
p "p" #=> "p"

module Kernel
  alias_method :original_p, :p
  undef :p
end

original_p "alias" #=> "alias"

begin
  p "hopeless, p is gone"
rescue => e
  puts e.inspect #=> #<NoMethodError: 'undefined method `p' for main'>
end

module Kernel
  alias_method :p, :original_p
  undef :original_p
end

p "p is back!" #=> "p is back!"
```
[Run it in Try Opal](http://opalrb.org/try/?code:p%20%22p%22%0Amodule%20Kernel%0A%20%20alias_method%20%3Aoriginal_p%2C%20%3Ap%0A%20%20undef%20%3Ap%0Aend%0Aoriginal_p%20%22alias%22%0Abegin%0A%20%20p%20%22hopeless%2C%20p%20is%20gone%22%0Arescue%20%3D%3E%20e%0A%20%20puts%20e.inspect%0Aend%0Amodule%20Kernel%0A%20%20alias_method%20%3Ap%2C%20%3Aoriginal_p%0A%20%20undef%20%3Aoriginal_p%0Aend%0Ap%20%22p%20is%20back!%22)

**Comment by zetachang** [comment]
Thanks! This is a cool trick! Will try out :+1:

**Comment by elia** [comment]
I'd suggest rather to just define p alongside method_missing

**Comment by vais** [comment]
@elia that makes a ton of sense :) @zetachang one way or another you will have to special-case the `p` method. Simply overriding it (defining it to do what you want) in the same scope as your `method_missing` per @elia's suggestion is much better than mucking with `Kernel` to trick `method_missing`.

**Comment by zetachang** [comment]
Opal 0.6 doesn't have `undef` support... so I use the trick as @elia suggested to redefine the method. Also do some method signature checking to invoke the original `Kernel.p` method.

**Comment by elia** [comment]
ouch! any reason it's not on 0.7?

**Comment by zetachang** [comment]
Still waiting source map support... lol

**Comment by elia** [comment]
I see, seems it's a major issue…

**Comment by zetachang** [comment]
It's not an issue to me actually. My main concern is that for those who start to use Opal because of this library will get lost in debugging compiled javascript.

**Comment by elia** [comment]
makes total sense, will try to find the time to attack the problem properly, unless @adambeynon or @ryanstout already made any progress…

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#7
