### ISSUE TITLE
For backwards compatibility make sure to always update react state when state changes

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#78]
Huh?  

For optimization the React::State module does not update the underlying react state hash unless somebody is looking at the particular state variable.

After all if nobody is looking than why update it?  (Very Zen!)

But to keep backwards compatibility, and perhaps in case for some reason you need to actually look at the react state hash, we will update it.   We can do this and avoid the re-render because we also have a "secret" state variable that only changes when observable state changes.  The default needs_update? method checks this value. By updating the underlying the state WITHOUT updating this we can avoid unnecessary re-renders, but keep the underlying react state consistent.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#78
