### ISSUE TITLE
Rewrite tests involving component#children method

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#79]
Formerly the `children` method was associated with the Element making them very difficult to use.  Now `children` is defined as one the component instance methods.  You can still get at the react children value by using props.children on the native element if for some reason you need to.

Meanwhile this requires 2 tests to be rewritten to interrogate the value of `children` once the test component is mounted.

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#79
