### ISSUE TITLE
params and states should be accessed via a "params" and "states" method

### ISSUE THREAD

**Issue by catmando** [zetachang/react.rb#83]
Currently if you declare a param or state it creates a instance method of the same name.

This can cause name conflicts with other methods, and also does not tell readers of the code what the special properities of the methods are.

So the suggestion is that we access states and properties via a method called states / params.  For example 
```ruby
defined_state :foo
required_param :bar
...
    state.foo # currently can just say foo
    param.bar # currently can just say bar
    # alternative syntax 1
    states.foo
    params.bar
    # alternative syntax 2
    state_foo
    param_bar
...
```

Questions for discussion:  
1) should the method be singular or plural, or just create the method like state_foo, param_bar
2) should we deprecate the current capability?  Why / why not?

**Comment by ajjahn** [comment]
1. I like `state.foo` / `param.bar`. I'm not sure about singular or plural. I'm experiencing some cognitive dissonance here. I think singular `state` and plural `params` reads most natural, but having the inconsistency is clearly wrong. 

2. Yes. We don't have to remove it right away, but I don't think we need to support both interfaces for the long term.

**Comment by catmando** [comment]
I think the problem is you talk about the state (singular) and the parameters (plural) of a component.  State is kind of like sheep or deer.  I could go with state/params

**Comment by ajjahn** [comment]
@catmando So `sheeps.foo` / `deers.bar`? Okay okay, enough tom foolery. That's a good point though. I'd be okay with state/params. The next question is should params be props?

**Comment by catmando** [comment]
yeah I don't know... I personally much prefer params (they just feel more like parameters than properties) but not sure how much confusion it makes.  
+ params gives a nod to rails, and will be familar to people coming from that background
+ params is what it is today and works
+ params allows "props" to be for low level access to the actual react props hash (ugh)
-  params makes it harder for react.js people (but not a lot I think)
-  params is longer than props

**Comment by ajjahn** [comment]
I agree. Params are beefed up props. The fact that they have more behavior than the underlying react props justifies making a distinction. Plus, it allows direct access to low level props if you need.

**Comment by Thermatix** [comment]
I agree @ajjahn, they have different behavior so should be kept distinct; I also prefer it with the the `.` as it feels more natural in my head and less 'magical'.

**Comment by catmando** [comment]
FYI... this also solves a nagging problem that we can't easily call a param "params" which react-router wants to do.  Now that params are scoped by the params method, and params.params works fine.

**Comment by fkchang** [comment]
state/params looks good to me.  Would still keep [] access too?

**Comment by catmando** [comment]
I don;t think so

**Comment by sollycatprint** [comment]
This issue was moved to reactrb/reactrb#83
